(() => {
  const KEY="miranda-gameplus-v1", BASE="miranda-expansion-v1";
  const scenes=[...document.querySelectorAll(".scene")], hub=document.getElementById("mirandaHub"), tabs=hub?.querySelector(".hub-tabs");
  if(!hub||!tabs||scenes.length!==23||document.querySelector('[data-hub-tab="gameplus"]'))return;
  const $=id=>document.getElementById(id);
  let s;try{s=JSON.parse(localStorage.getItem(KEY))||{}}catch{s={}}
  s.xp=Number(s.xp)||0;s.coins=Number(s.coins)||0;s.awards=s.awards||{};s.collectibles=Array.isArray(s.collectibles)?s.collectibles:[];s.shop=Array.isArray(s.shop)?s.shop:[];s.equipped=Array.isArray(s.equipped)?s.equipped:[];s.rabbitHits=Number(s.rabbitHits)||0;s.clicks=Number(s.clicks)||0;s.rareEvents=Number(s.rareEvents)||0;s.oracleUses=Number(s.oracleUses)||0;s.diceUses=Number(s.diceUses)||0;s.ngplus=!!s.ngplus;s.ngFragments=Array.isArray(s.ngFragments)?s.ngFragments:[];s.daily=s.daily||{};s.dailyVisited=Array.isArray(s.dailyVisited)?s.dailyVisited:[];
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}};
  const parse=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const tab=document.createElement("button");tab.type="button";tab.dataset.hubTab="gameplus";tab.textContent="Juego+";tabs.appendChild(tab);
  const panel=document.createElement("section");panel.className="hub-panel gameplus-panel";panel.dataset.hubPanel="gameplus";
  panel.innerHTML=[
    '<div class="game-profile"><div class="game-avatar"><span>✦</span><small>NIVEL</small><strong id="gpLevel">1</strong></div><div class="game-profile-main"><span class="kicker">Modo Juego+</span><h3 id="gpRank">Curiosa</h3><div class="gp-xp"><span id="gpXpBar"></span></div><div class="gp-xp-meta"><small id="gpXpText">0 XP</small><small id="gpNextText"></small></div></div><div class="gp-wallet"><span>✦</span><strong id="gpCoins">0</strong><small>Miranditos</small></div></div>',
    '<div class="gp-grid">',
      '<article class="gp-card"><small>MISIÓN DEL DÍA</small><h4 id="dailyTitle">Cargando…</h4><p id="dailyText"></p><div class="daily-progress"><span id="dailyBar"></span></div><div class="daily-meta"><span id="dailyCount">0/1</span><strong>+25 XP · +8 ✦</strong></div></article>',
      '<article class="gp-card gp-chaos"><small>DADO DEL CAOS</small><h4>Deja que decida la web</h4><div class="chaos-die" id="chaosDie">?</div><p id="chaosResult">Plan, pregunta, recuerdo, reto, secreto…</p><button class="secondary" id="rollChaos">Tirar el dado 🎲</button></article>',
      '<article class="gp-card"><small>ORÁCULO DE MIRANDA</small><h4>Predicción completamente científica*</h4><p id="oracleText">Consulta el oráculo.</p><button class="secondary" id="askOracle">Consultar 🔮</button><em>*probablemente no</em></article>',
      '<article class="gp-card gp-news"><small>MIRANDA TIMES</small><h4 id="newsHeadline">Última hora</h4><p id="newsBody">La investigación continúa.</p><button class="secondary" id="refreshNews">Nueva portada 📰</button></article>',
    '</div>',
    '<div class="gp-section-head"><div><span class="kicker">Colección</span><h3>Vitrina de recuerdos</h3></div><small>Se desbloquean explorando</small></div><div class="collectible-grid" id="collectibleGrid"></div>',
    '<div class="gp-section-head"><div><span class="kicker">Tienda</span><h3>Gasta tus Miranditos</h3></div><small>Solo efectos decorativos</small></div><div class="shop-grid" id="shopGrid"></div>',
    '<div class="gp-section-head"><div><span class="kicker">Código maestro</span><h3>23 fragmentos</h3></div><small id="masterCodeStatus">0/23</small></div><div class="master-code-card"><div class="master-fragments" id="masterFragments"></div><div id="masterCodeReveal">El código sigue oculto.</div></div>',
    '<div class="gp-final-grid"><article class="gp-card"><small>INFORME FINAL</small><h4>Expediente de exploración</h4><p>Todo el progreso en una ficha.</p><button class="secondary" id="openReport">Ver informe →</button></article><article class="gp-card"><small>CERTIFICADO</small><h4>Exploradora oficial</h4><p id="certificateText">Abre la Página 24 para habilitarlo.</p><button class="secondary" id="openCertificate" disabled>Bloqueado</button></article><article class="gp-card gp-ngplus"><small>PROGRESO IMPOSIBLE</small><h4 id="ngTitle">100% → 101%</h4><p id="ngText">Primero abre la Página 24.</p><div class="ng-progress"><span id="ngBar"></span></div><button class="primary" id="startBoss" disabled>Jefe final bloqueado</button></article></div>'
  ].join("");
  hub.querySelector(".miranda-hub-shell").appendChild(panel);
  tab.onclick=()=>{hub.querySelectorAll("[data-hub-tab]").forEach(b=>b.classList.toggle("active",b===tab));hub.querySelectorAll("[data-hub-panel]").forEach(p=>p.classList.toggle("active",p===panel));render()};

  const toast=document.createElement("div");toast.className="gp-toast";document.body.appendChild(toast);
  function note(a,b){toast.innerHTML="<strong>"+esc(a)+"</strong><span>"+esc(b)+"</span>";toast.classList.add("show");clearTimeout(toast._t);toast._t=setTimeout(()=>toast.classList.remove("show"),2500)}
  function base(){
    const d=parse("miranda-23-details-v1",{found:[]}),e=parse("miranda-exploration-v1",{achievements:[]}),m=parse("miranda-microdetails-v1",{tokens:[]}),x=parse(BASE,{visited:[],capsules:[],page24Opened:false}),p=parse("miranda-plans-v1",{plans:[]}),h=parse("miranda-hints-v1",{used:0}),a=Array.isArray(e.achievements)?e.achievements:[];
    return{details:Array.isArray(d.found)?d.found:[],ach:a,total:(window.mirandaAchievementIds||[]).length||Math.max(16,a.length),tokens:Array.isArray(m.tokens)?m.tokens:[],visited:Array.isArray(x.visited)?x.visited:[],capsules:Array.isArray(x.capsules)?x.capsules:[],page24Opened:!!x.page24Opened,plans:Array.isArray(p.plans)?p.plans:[],hints:Number(h.used)||0}
  }
  function award(id,xp,c,label){if(s.awards[id])return;s.awards[id]=1;s.xp+=xp;s.coins+=c;save();if(label)note("Recompensa",label+" · +"+xp+" XP · +"+c+" ✦")}
  function col(id,label){if(s.collectibles.includes(id))return;s.collectibles.push(id);save();note("Nuevo coleccionable",label)}
  function sync(){
    const b=base();b.visited.forEach(x=>award("v:"+x,2,0));b.details.forEach(x=>award("d:"+x,6,2));b.tokens.forEach(x=>award("t:"+x,15,4));b.ach.forEach(x=>award("a:"+x,12,3));
    if(b.details.length)col("star","Primera estrella");if(new Set(b.visited).size>=8)col("compass","Brújula curiosa");if(b.ach.length>=5)col("key","Llave del archivo");if(b.plans.length)col("ticket","Entrada de plan");if(b.capsules.length)col("moon","Cápsula lunar");if(b.details.length>=23)col("crown","Corona 23");if(s.rabbitHits>=3)col("rabbit","Conejo fugitivo");if(s.ngFragments.length>=5)col("black","Fragmento 101");return b
  }
  function lev(){const n=Math.min(23,Math.floor(s.xp/20)+1),a=(n-1)*20,z=n>=23?a:n*20,p=n>=23?100:Math.max(0,Math.min(100,(s.xp-a)/(z-a)*100));let r="Curiosa";if(n>=5)r="Exploradora";if(n>=10)r="Detective";if(n>=15)r="Cazasecretos";if(n>=20)r="Miranda Legendaria";if(n>=23)r=s.ngplus?"Miranda 101":"Leyenda del Archivo";return{n,z,p,r}}
  function profile(){const l=lev();$("gpLevel").textContent=l.n;$("gpRank").textContent=l.r;$("gpXpBar").style.width=l.p+"%";$("gpXpText").textContent=s.xp+" XP";$("gpNextText").textContent=l.n>=23?"Nivel máximo":"Siguiente: "+l.z+" XP";$("gpCoins").textContent=s.coins}

  function dcfg(){const date=new Date().toISOString().slice(0,10),q=[["random","Confía en el azar","Usa «Estoy aburrida».",1],["slot","Plan de laboratorio","Genera un plan combinado.",1],["hint","Detective con ayuda","Pide una pista.",1],["scene","Turismo interno","Visita 3 capítulos distintos.",3],["dice","Caos controlado","Tira el Dado del Caos.",1]],i=[...date].reduce((a,c)=>a+c.charCodeAt(0),0)%q.length;return{date,type:q[i][0],title:q[i][1],text:q[i][2],goal:q[i][3]}}
  function dailyInit(){const c=dcfg();if(s.daily.date!==c.date){s.daily={date:c.date,type:c.type,title:c.title,text:c.text,goal:c.goal,progress:0,done:false};s.dailyVisited=[];save()}}
  function daily(type,val){dailyInit();if(s.daily.done||s.daily.type!==type)return;if(type==="scene"){if(s.dailyVisited.includes(val))return;s.dailyVisited.push(val);s.daily.progress=Math.min(s.daily.goal,s.dailyVisited.length)}else s.daily.progress=Math.min(s.daily.goal,(Number(s.daily.progress)||0)+1);if(s.daily.progress>=s.daily.goal){s.daily.done=true;s.xp+=25;s.coins+=8;note("Misión completada","+25 XP · +8 Miranditos")}save();render()}
  function dailyView(){dailyInit();$("dailyTitle").textContent=s.daily.title;$("dailyText").textContent=s.daily.done?"Completada por hoy. Mañana habrá otra.":s.daily.text;$("dailyCount").textContent=s.daily.progress+"/"+s.daily.goal;$("dailyBar").style.width=Math.min(100,s.daily.progress/s.daily.goal*100)+"%"}

  const cols=[["star","✦","Primera estrella","Primer detalle."],["compass","⌖","Brújula curiosa","8 capítulos."],["key","◇","Llave del archivo","5 logros."],["ticket","▱","Entrada de plan","Un plan guardado."],["moon","☾","Cápsula lunar","Una cápsula propia."],["crown","♕","Corona 23","23 detalles."],["rabbit","♢","Conejo fugitivo","3 capturas."],["black","◆","Fragmento 101","New Game+ completo."]];
  function colView(){$("collectibleGrid").innerHTML=cols.map(c=>'<article class="collectible '+(s.collectibles.includes(c[0])?"unlocked":"locked")+'"><span>'+c[1]+'</span><strong>'+c[2]+'</strong><small>'+c[3]+'</small><em>'+(s.collectibles.includes(c[0])?"DESBLOQUEADO":"???")+'</em></article>').join("")}
  const shop=[["sparkles","Polvo de estrellas","Estrellas flotantes.",15],["glow","Halo secreto","Resplandor del Centro 23.",25],["archive","Modo archivo","Estética de expediente.",35]];
  function effects(){document.body.classList.toggle("gp-glow",s.equipped.includes("glow"));document.body.classList.toggle("gp-archive",s.equipped.includes("archive"));let l=$("gpStarLayer");if(s.equipped.includes("sparkles")&&!l){l=document.createElement("div");l.id="gpStarLayer";l.className="gp-star-layer";l.innerHTML=Array.from({length:18},(_,i)=>'<i style="left:'+((i*37)%100)+'%;top:'+((i*53)%95)+'%">✦</i>').join("");document.body.appendChild(l)}else if(!s.equipped.includes("sparkles"))l?.remove()}
  function shopView(){$("shopGrid").innerHTML=shop.map(x=>{const own=s.shop.includes(x[0]),on=s.equipped.includes(x[0]);return'<article class="shop-item"><strong>'+x[1]+'</strong><small>'+x[2]+'</small><button class="secondary" data-shop="'+x[0]+'">'+(own?(on?"Quitar":"Usar"):x[3]+" ✦")+'</button></article>'}).join("");$("shopGrid").querySelectorAll("[data-shop]").forEach(b=>b.onclick=()=>{const x=shop.find(y=>y[0]===b.dataset.shop);if(!s.shop.includes(x[0])){if(s.coins<x[3])return note("Saldo insuficiente","Te faltan "+(x[3]-s.coins)+" Miranditos.");s.coins-=x[3];s.shop.push(x[0]);s.equipped.push(x[0]);note("Compra desbloqueada",x[1])}else s.equipped=s.equipped.includes(x[0])?s.equipped.filter(z=>z!==x[0]):[...s.equipped,x[0]];save();render()})}

  const chaos=[["1","PLAN · Gira la ruleta y acepta el primer resultado.","plans"],["2","PREGUNTA · ¿Qué momento repetirías exactamente igual?",""],["3","RECUERDO · Abre una foto y cuenta lo que no aparece escrito.","gallery"],["4","RETO · Marca una casilla del bingo para este mes.","bingo"],["5","SECRETO · Ve al primer capítulo pendiente.","pending"],["6","CAOS · El dado se niega a colaborar. Vuelve a tirar.",""]];
  $("rollChaos").onclick=()=>{s.diceUses++;save();daily("dice");const x=chaos[Math.floor(Math.random()*chaos.length)];$("chaosDie").textContent=x[0];$("chaosDie").classList.remove("roll");void $("chaosDie").offsetWidth;$("chaosDie").classList.add("roll");$("chaosResult").textContent=x[1];if(x[2]&&x[2]!=="pending")setTimeout(()=>go(x[2]),700);if(x[2]==="pending"){const b=base(),t=scenes.find(n=>!b.details.includes(n.dataset.sceneId));if(t)setTimeout(()=>go(t.dataset.sceneId),700)}award("dice:first",8,2,"Primer lanzamiento del caos");render()};
  const oracle=["Hay un 92% de posibilidades de que hoy apetezca algo dulce.","La próxima buena idea aparecerá después de decir «no sé qué hacer».","Una foto antigua será más graciosa de lo que recuerdas.","El oráculo recomienda un paseo sin rumbo.","Se detecta una alta probabilidad de plan improvisado.","Buen día para crear una cápsula del tiempo.","Todavía queda un botón sospechoso por pulsar."];
  $("askOracle").onclick=()=>{s.oracleUses++;save();$("oracleText").textContent=oracle[Math.floor(Math.random()*oracle.length)];if(s.oracleUses===3)award("oracle:3",10,3,"Tres consultas al oráculo");render()};
  function news(random=false){const b=base(),l=lev(),a=[["EXCLUSIVA: Miranda alcanza nivel "+l.n,"El Archivo 23 empieza a preocuparse."],["ÚLTIMA HORA: "+b.details.length+" detalles localizados","Los botones sospechosos están siendo interrogados."],["ECONOMÍA: "+s.coins+" Miranditos en circulación","No los gastes todos en estrellas."],["SOCIEDAD: "+b.plans.length+" planes archivados","La ruleta niega responsabilidades."],["MISTERIO: "+s.rabbitHits+" conejos avistados","Aparecen cuando nadie lo espera."]],i=random?Math.floor(Math.random()*a.length):(b.details.length+s.rabbitHits)%a.length;$("newsHeadline").textContent=a[i][0];$("newsBody").textContent=a[i][1]}
  $("refreshNews").onclick=()=>{news(true);award("news:first",5,1)};

  function master(){const b=base(),code="MIRANDA23ARCHIVOSECRETOXX";$("masterFragments").innerHTML=Array.from({length:23},(_,i)=>'<span class="'+(i<b.details.length?"found":"")+'">'+(i<b.details.length?(code[i]||"✦"):"?")+'</span>').join("");$("masterCodeStatus").textContent=b.details.length+"/23";$("masterCodeReveal").innerHTML=b.details.length>=23?'Código reconstruido: <strong>MIRANDA23</strong>':"El código sigue oculto."}
  const over=document.createElement("div");over.className="gp-overlay hidden";over.innerHTML='<div class="gp-overlay-card"><button class="gp-overlay-close">×</button><div id="gpOverlayContent"></div></div>';document.body.appendChild(over);over.querySelector(".gp-overlay-close").onclick=()=>over.classList.add("hidden");
  $("openReport").onclick=()=>{const b=base(),l=lev();$("gpOverlayContent").innerHTML='<span class="kicker">Informe final</span><h2>Expediente Miranda #23</h2><div class="report-rank"><span>Nivel '+l.n+'</span><strong>'+esc(l.r)+'</strong></div><div class="report-grid"><div><strong>'+new Set(b.visited).size+'/23</strong><small>visitados</small></div><div><strong>'+b.details.length+'/23</strong><small>detalles</small></div><div><strong>'+b.tokens.length+'/5</strong><small>mini secretos</small></div><div><strong>'+b.ach.length+'/'+b.total+'</strong><small>logros</small></div><div><strong>'+b.hints+'</strong><small>pistas</small></div><div><strong>'+b.plans.length+'</strong><small>planes</small></div><div><strong>'+s.rabbitHits+'</strong><small>conejos</small></div><div><strong>'+s.rareEvents+'</strong><small>eventos raros</small></div></div>';over.classList.remove("hidden")};
  $("openCertificate").onclick=()=>{const l=lev();$("gpOverlayContent").innerHTML='<div class="certificate"><span>✦ CERTIFICADO OFICIAL DEL ARCHIVO 23 ✦</span><h2>Miranda</h2><p>ha completado oficialmente <strong>Sorpresa‑Miranda</strong> y queda reconocida como</p><h3>'+esc(l.r)+'</h3><small>23 capítulos · secretos · demasiada curiosidad</small><div class="certificate-seal">23</div></div>';over.classList.remove("hidden")};

  const boss=document.createElement("div");boss.className="boss-overlay hidden";boss.innerHTML='<div class="boss-card"><button class="boss-close">×</button><span class="kicker">Jefe final</span><h2>El Archivo no abrirá el 101% tan fácilmente.</h2><div id="bossStage"></div></div>';document.body.appendChild(boss);boss.querySelector(".boss-close").onclick=()=>boss.classList.add("hidden");let step=0;
  function bossView(){const q=$("bossStage");if(step===0)q.innerHTML='<p>Prueba 1/3 · ¿Cuántos capítulos tiene el recorrido normal?</p><div class="boss-options"><button data-v="22">22</button><button data-v="23">23</button><button data-v="24">24</button></div>';if(step===1)q.innerHTML='<p>Prueba 2/3 · Introduce el código maestro.</p><div class="boss-input"><input id="bossCode" placeholder="Código"><button id="bossCodeBtn">Validar</button></div>';if(step===2)q.innerHTML='<p>Prueba 3/3 · ¿Qué símbolo aparece por toda la web?</p><div class="boss-options"><button data-v="heart">♥</button><button data-v="star">✦</button><button data-v="moon">☾</button></div>';q.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{const ok=(step===0&&b.dataset.v==="23")||(step===2&&b.dataset.v==="star");if(!ok)return note("Incorrecto","El archivo sigue cerrado.");step++;if(step>=3)return defeat();bossView()});$("bossCodeBtn")?.addEventListener("click",()=>{if(($("bossCode").value||"").toUpperCase().replace(/[^A-Z0-9]/g,"")!=="MIRANDA23")return note("Código rechazado","No coincide.");step=2;bossView()})}
  function defeat(){s.ngplus=true;s.xp+=40;s.coins+=12;save();boss.classList.add("hidden");note("NEW GAME+ DESBLOQUEADO","100% ya no es el final.");render()}
  $("startBoss").onclick=()=>{if(s.ngplus)return note("New Game+","Ya está activo. Busca ◆.");if(!base().page24Opened)return note("Bloqueado","Primero abre la Página 24.");step=0;bossView();boss.classList.remove("hidden")};

  const ng=[["timeline","n1","Fragmento I"],["gallery","n2","Fragmento II"],["secrets","n3","Fragmento III"],["cinema","n4","Fragmento IV"],["finale","n5","Fragmento V"]];
  function inject(){ng.forEach(x=>{const sc=scenes.find(n=>n.dataset.sceneId===x[0]);if(!sc||sc.querySelector('[data-ng="'+x[1]+'"]'))return;const b=document.createElement("button");b.className="ng-fragment";b.dataset.ng=x[1];b.innerHTML="<span>◆</span><small>"+x[2]+"</small>";b.onclick=()=>{if(!s.ngplus||s.ngFragments.includes(x[1]))return;s.ngFragments.push(x[1]);s.xp+=18;s.coins+=5;save();note(x[2],"Encontrado · +18 XP · +5 ✦");render()};sc.appendChild(b)})}
  function ngView(){const b=base(),p=Math.min(1,s.ngFragments.length/5);$("openCertificate").disabled=!b.page24Opened;$("openCertificate").textContent=b.page24Opened?"Ver certificado":"Bloqueado";$("certificateText").textContent=b.page24Opened?"Página 24 abierta. Certificado disponible.":"Abre la Página 24 para habilitarlo.";$("ngBar").style.width=p*100+"%";if(s.ngplus){$("ngTitle").textContent=(100+p).toFixed(1).replace(".0","")+"% · New Game+";$("ngText").textContent=s.ngFragments.length>=5?"101% completado.":"Busca cinco símbolos ◆ en capítulos conocidos.";$("startBoss").disabled=false;$("startBoss").textContent=s.ngFragments.length>=5?"101% completado ✓":"New Game+ · "+s.ngFragments.length+"/5"}else if(b.page24Opened){$("ngText").textContent="La Página 24 está abierta. Jefe final disponible.";$("startBoss").disabled=false;$("startBoss").textContent="Iniciar jefe final →"}else{$("startBoss").disabled=true;$("startBoss").textContent="Jefe final bloqueado"}document.body.classList.toggle("ngplus-active",s.ngplus);document.querySelectorAll(".ng-fragment").forEach(x=>{x.classList.toggle("available",s.ngplus&&!s.ngFragments.includes(x.dataset.ng));x.classList.toggle("found",s.ngFragments.includes(x.dataset.ng))})}
  function go(id){const i=scenes.findIndex(x=>x.dataset.sceneId===id);if(i<0)return;hub.classList.add("hidden");document.body.classList.remove("hub-open");window.mirandaShowScene?window.mirandaShowScene(i):(scenes.forEach((x,n)=>x.classList.toggle("active",n===i)),scrollTo({top:0,behavior:"smooth"}))}
  function rabbit(){if(s.rabbitHits>=3||document.querySelector(".secret-rabbit")||s.clicks<8||s.clicks%11)return;const b=document.createElement("button");b.className="secret-rabbit";b.textContent="◇";b.style.left=(10+Math.random()*78)+"vw";b.style.top=(15+Math.random()*65)+"vh";document.body.appendChild(b);b.onclick=e=>{e.stopPropagation();s.rabbitHits++;s.xp+=10;s.coins+=4;save();b.remove();note("¡Conejo atrapado!",s.rabbitHits+"/3 · +10 XP · +4 ✦");render()};setTimeout(()=>b.remove(),4200)}
  function glitch(){s.rareEvents++;save();const g=document.createElement("div");g.className="gp-glitch";g.innerHTML="<strong>ERROR 101</strong><span>final_no_encontrado.exe</span>";document.body.appendChild(g);setTimeout(()=>g.remove(),1100)}
  document.addEventListener("click",e=>{if(e.target.closest(".secret-rabbit"))return;s.clicks++;save();rabbit();if(s.clicks%37===0)glitch();if(e.target.closest("#randomPick"))daily("random");if(e.target.closest("#slotSpin"))daily("slot");if(e.target.closest(".hint-more"))daily("hint");setTimeout(render,90)},true);
  const ob=new MutationObserver(()=>{const a=scenes.find(x=>x.classList.contains("active"));if(a)daily("scene",a.dataset.sceneId);setTimeout(render,80)});scenes.forEach(x=>ob.observe(x,{attributes:true,attributeFilter:["class"]}));
  function render(){sync();profile();dailyView();colView();shopView();master();news();effects();inject();ngView()}
  dailyInit();render();window.mirandaGamePlus={render,note};
})();